In [1]:
import tensorflow as tf

In [2]:
x = tf.random.uniform(shape=[10,2])
print(x.numpy())

Metal device set to: Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB

[[0.69398546 0.27671897]
 [0.29323745 0.00516176]
 [0.55283546 0.65660274]
 [0.23537064 0.80176866]
 [0.17887044 0.8596202 ]
 [0.846836   0.670519  ]
 [0.9409584  0.31553543]
 [0.84110427 0.7054851 ]
 [0.02943313 0.09644127]
 [0.8367977  0.66402113]]


2023-01-27 13:30:32.446372: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-01-27 13:30:32.446875: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [9]:
print(x[:,1:2].numpy())

[[0.27671897]
 [0.00516176]
 [0.65660274]
 [0.80176866]
 [0.8596202 ]
 [0.670519  ]
 [0.31553543]
 [0.7054851 ]
 [0.09644127]
 [0.66402113]]


In [11]:
import numpy as np

In [12]:
n = np.array([1.,2.,3.])
n[0]

1.0

In [13]:
n[None,0]

array([1.])